server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  kafka:
    topics:
      user-stream: user-stream-topic
      user-flow: user-flow-topic
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

keycloak:
  url: http://localhost:8082
  realm: auth-realm
  admin:
    username: admin
    password: admin
